# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
    schedule:
        -   cron: '5 16 * * *'
    workflow_dispatch:
    watch:
        types: [ started ]
env:
    TZ: Asia/Shanghai
jobs:
    run:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2
            -   name: Set up Python 3.7
                uses: actions/setup-python@v2
                with:
                    python-version: 3.7
            -   name: Install dependencies
                run: |
                    python -m pip install --upgrade pip
                    pip install requests
                    pip install beautifulsoup4
            -   name: AutoDaily
                env:
                    TX_API: ${{ secrets.TX_API }}
                    XZ_API: ${{ secrets.XZ_API }}
                    EMAIL: ${{ secrets.EMAIL }}
                    YOUYUN_ID1: ${{ secrets.YOUYUN_ID1 }}
                    YOUYUN_ID2: ${{ secrets.YOUYUN_ID2 }}
                    YOUYUN_PWD: ${{ secrets.YOUYUN_PWD }}
                run: python app.py
